### ISSUE TITLE
Remove "Chat with Assistant" Headline 

### ISSUE THREAD

**Issue by rrolf** [virtUOS/kiwi#29]
As the assistant options are currently removed that prompt is irritating. 
Maybe a very prominent message that OpenAIs GPT is used and no private data should be included would be good.

**Comment by Odrec** [comment]
Something like this? This is based on how ChatGPT interface looks with a basic welcoming message

![Screenshot from 2024-02-27 13-26-52](https://github.com/virtUOS/kiwi/assets/9385209/c39126e3-6152-4328-a724-ac729dc5f6c5)
