### ISSUE TITLE
change the toggle option "Kamera aktivieren" to a click-button such as the one with "Bilder hochladen" 

### ISSUE THREAD

**Issue by svensandscheper** [virtUOS/kiwi#40]
I think this would be more consistent if possible

**Comment by rrolf** [comment]
<img width="816" alt="Bildschirmfoto 2024-06-11 um 13 44 34" src="https://github.com/virtUOS/kiwi/assets/1894165/4e8ace7e-4e79-478f-ac03-3565ba26c61e">

The left camera button opens the camera dialogue. An additional button close camera would be needed there too.

**Comment by Odrec** [comment]
I agree that having a separate button for the camera is probably better than having it inside the popover with the other image controls. It makes it easier for the user to turn the camera on and off without additional clicks.
