### ISSUE TITLE
change the emoji of "Bilder hochladen"-button to something more fitting to what it does

### ISSUE THREAD

**Issue by svensandscheper** [virtUOS/kiwi#41]
I would not know, what function the button has without clicking on it. Alternatives:
🖼️ as in galerie

or maybe we also move it to the camera button? If I am a user and I want to do anything with pictures, I click on the camera-icon and choose between using my camera, uploading or inserting an URL.

**Comment by rrolf** [comment]
<img width="816" alt="Bildschirmfoto 2024-06-11 um 13 44 34" src="https://github.com/virtUOS/kiwi/assets/1894165/fa03a970-00d5-4732-bc77-a58439d29c4c">

Suggestion to use Google Material icons, instead all current icons. 

By the way, move delete chat back to the chat controls.

**Comment by Odrec** [comment]
About the icons, this is what they answered me on the github issue. So the google icons can't be used for labels yet. There's an issue open for that so vote it up for it to be implemented quicker.

https://github.com/streamlit/streamlit/issues/7273#issuecomment-2159450700 

This is the current open issue

https://github.com/streamlit/streamlit/issues/8783

I haven't seen any workaround yet but I'll keep looking.
